# Generated by Django 4.0.3 on 2022-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='123abc', max_length=20),
        ),
    ]
