# Generated by Django 4.0.3 on 2022-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kite', '0002_userdata_email_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
